# ENV variables
ENV_MINIMAX_API_KEY = "MINIMAX_API_KEY"
ENV_MINIMAX_API_HOST = "MINIMAX_API_HOST"
ENV_FASTMCP_LOG_LEVEL = "FASTMCP_LOG_LEVEL"
ENV_MINIMAX_MCP_TRANSPORT = "MINIMAX_MCP_TRANSPORT"
ENV_MINIMAX_MCP_HOST = "MINIMAX_MCP_HOST"
ENV_MINIMAX_MCP_PORT = "MINIMAX_MCP_PORT"
ENV_MINIMAX_MCP_BEARER_TOKEN = "MINIMAX_MCP_BEARER_TOKEN"
